// Variables
const prenda = [
    {
        "id": 1,
        "imagen": "img/prendas/bebenina/beba.jpeg",
        "nombre": "4Pack Body Manga Larga",
        "marca": "Bebitus",
        "precio": 80,
        "categoria": "Bebe Niña",
        "descuento": 0,
        "tallas1": ["RN"],
        "tallas2": ["6M"],
        "tallas3": ["9M"],
        "tallas4": ["12M"],
        "tallas5": ["18M"],
    },
    {
        "id": 2,
        "imagen": "img/prendas/bebenina/casacaBeba.jpeg",
        "nombre": "Casaca Minnie Rosa",
        "marca": "Bebitus",
        "precio": 155,
        "categoria": "Bebe Niña",
        "descuento": 0,
        "tallas1": ["RN"],
        "tallas2": ["6M"],
        "tallas3": ["9M"],
        "tallas4": ["12M"],
        "tallas5": ["18M"],
    },
    {
        "id": 3,
        "imagen": "img/prendas/bebenina/chalecoBeba.jpeg",
        "nombre": "Chaleco Minnie Mora",
        "marca": "Bebitus",
        "precio": 120,
        "categoria": "Bebe Niña",
        "descuento": 0,
        "tallas1": ["RN"],
        "tallas2": ["6M"],
        "tallas3": ["9M"],
        "tallas4": ["12M"],
        "tallas5": ["18M"],
    },
    {
        "id": 4,
        "imagen": "img/prendas/bebenino/bodybebo.jpeg",
        "nombre": "3Pack Bodys Disney",
        "marca": "Bebitus",
        "precio": 80,
        "categoria": "Bebe Niño",
        "descuento": 0,
        "tallas1": ["RN"],
        "tallas2": ["6M"],
        "tallas3": ["9M"],
        "tallas4": ["12M"],
        "tallas5": ["18M"],
    },
    {
        "id": 5,
        "imagen": "img/prendas/bebenino/bebo.jpeg",
        "nombre": "3Pack Bodys Manga Larga",
        "marca": "Bebitus",
        "precio": 20,
        "categoria": "Bebe Niño",
        "descuento": 0,
        "tallas1": ["RN"],
        "tallas2": ["6M"],
        "tallas3": ["9M"],
        "tallas4": ["12M"],
        "tallas5": ["18M"],
    },
    {
        "id": 6,
        "imagen": "img/prendas/bebenino/buzoBebo.jpeg",
        "nombre": "Buzo Mickey Color Entero",
        "marca": "Bebitus",
        "precio": 20,
        "categoria": "Bebe Niño",
        "descuento": 0,
        "tallas1": ["RN"],
        "tallas2": ["6M"],
        "tallas3": ["9M"],
        "tallas4": ["12M"],
        "tallas5": ["18M"],
    },
    {
        "id": 7,
        "imagen": "img/prendas/nina/vestidonina.jpeg",
        "nombre": "Vestido Frozen Celeste",
        "marca": "Bebitus",
        "precio": 120,
        "categoria": "Niña",
        "descuento": 0,
        "tallas1": ["2"],
        "tallas2": ["4"],
        "tallas3": ["6"],
        "tallas4": ["8"],
        "tallas5": ["10"],
        "tallas6": ["12"]
    },
    {
        "id": 8,
        "imagen": "img/prendas/nina/chompanina.jpeg",
        "nombre": "Chompa Disney Rosa Niña",
        "marca": "Bebitus",
        "precio": 80,
        "categoria": "Niña",
        "descuento": 0,
        "tallas1": ["2"],
        "tallas2": ["4"],
        "tallas3": ["6"],
        "tallas4": ["8"],
        "tallas5": ["10"],
        "tallas6": ["12"]
    },
    {
        "id": 9,
        "imagen": "img/prendas/nina/vestidosnina.jpeg",
        "nombre": "Vestido Frozen Mora",
        "marca": "Bebitus",
        "precio": 120,
        "categoria": "Niña",
        "descuento": 0,
        "tallas1": ["2"],
        "tallas2": ["4"],
        "tallas3": ["6"],
        "tallas4": ["8"],
        "tallas5": ["10"],
        "tallas6": ["12"]
    },
    {
        "id": 10,
        "imagen": "img/prendas/nino/polonino.jpeg",
        "nombre": "Polo Spiderman Celeste",
        "marca": "Bebitus",
        "precio": 50,
        "categoria": "Niño",
        "descuento": 0,
        "tallas1": ["2"],
        "tallas2": ["4"],
        "tallas3": ["6"],
        "tallas4": ["8"],
        "tallas5": ["10"],
        "tallas6": ["12"]
    },
    {
        "id": 11,
        "imagen": "img/prendas/nino/polo3nino.jpeg",
        "nombre": "Polo Mickey Color entero",
        "marca": "Bebitus",
        "precio": 50,
        "categoria": "Niño",
        "descuento": 0,
        "tallas1": ["2"],
        "tallas2": ["4"],
        "tallas3": ["6"],
        "tallas4": ["8"],
        "tallas5": ["10"],
        "tallas6": ["12"]
    },
    {
        "id": 12,
        "imagen": "img/prendas/nino/chompanono.jpeg",
        "nombre": "Chompa Batman Negro",
        "marca": "Bebitus",
        "precio": 90,
        "categoria": "Niño",
        "descuento": 0,
        "tallas1": ["2"],
        "tallas2": ["4"],
        "tallas3": ["6"],
        "tallas4": ["8"],
        "tallas5": ["10"],
        "tallas6": ["12"]
    }


];